# Generated by Django 5.1.1 on 2024-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionsgame',
            name='num_categories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='connectionsgame',
            name='words_per_category',
            field=models.IntegerField(),
        ),
    ]
