# Generated by Django 5.1.1 on 2024-09-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0002_alter_connectionsgame_num_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='connections_game',
            new_name='related_game',
        ),
    ]
