# Generated by Django 5.1.1 on 2024-09-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0003_rename_connections_game_category_related_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='explanation',
            field=models.TextField(default='No explanation provided'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_py_code',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='connectionsgame',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='related_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='connections_app.connectionsgame'),
        ),
        migrations.AlterField(
            model_name='connectionsgame',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
