# Generated by Django 5.1.1 on 2024-09-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0004_category_explanation_category_is_py_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='connections_app.connectionsgame'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guesses', models.JSONField()),
                ('time_taken', models.JSONField()),
                ('is_won', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections_app.connectionsgame')),
            ],
        ),
    ]
